# Generated by Django 4.1.9 on 2023-08-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=50)),
                ('question_content', models.CharField(max_length=500)),
                ('question_date', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.DO_NOTHING, to='board.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_title', models.CharField(max_length=50)),
                ('answer_content', models.CharField(max_length=500)),
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.question')),
                ('user_email', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.DO_NOTHING, to='board.user')),
            ],
            options={
                'unique_together': {('answer_id', 'question')},
            },
        ),
    ]
